apiVersion: v1
kind: ConfigMap
metadata:
  name: bult-in-policy
  namespace: kube-system
data:
 policy.cfg : |
  {
    "kind" : "Policy",
    "apiVersion" : "v1",
    "predicates" : [ 
      {"name" : "PodFitsResources"}
    ],
    "priorities" : [ 
      {"name" : "LeastRequestedPriority", "weight" : 1}
    ],
    "hardPodAffinitySymmetricWeight" : 10
  }