apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-rs
  labels:
    app: nginx
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      schedulerName: my-scheduler
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: "1"
            memory: 1024Mi