apiVersion: extensions/v1
kind: ReplicaSet
metadata:
  name: hello-minikube
spec:
  replicas: 2
    template:　　#pod的模板定义 
        metadata:
          name: test-pod
        spec:
          schedulerName: my-scheduler
          containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 80