apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-minikube
spec:
  replicas: 2
  selector:
    template:
      metadata:
        labels:
          run: nginx
      spec:
        containers:
                - name: nginx
                  image: nginx
                  ports:
                  - containerPort: 80