apiVersion: v1
kind: Deployment
metadata:
  name: test-pod
spec:
  replicas: 30
  schedulerName: my-scheduler
   template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
